### ISSUE TITLE
Kan inte gå ur brottsregister menyn.

### ISSUE THREAD

**Issue by calmitup** [jonassvensson4/jsfour-brottsregister#1]
Tjena.

Jag noterade att man blir fryst när man ska gå ur menyn.

Även så undrar jag vart eller hur man adderar information till databasen?

Annars ett grymt script!

/Calm

**Comment by jnsvns** [comment]
Det fungerar visst att gå ut från menyn. Fungerar det inte har du troligtvis fel namn på scriptet. Det ska heta jsfour-brottsregister. Heter det något annat så kommer det inte fungera.  Annars vet jag inte vad det kan vara då det fungerar för mig och för alla andra. 

Sen när det gäller frågor om hur man använder det så står det en liten text att det får man ta reda på själv då jag egentligen inte ville släppa det för allmänheten. Kolla på servern så ser du vad för events det finns.

**Comment by calmitup** [comment]
Okej.

Jag hade självklart ändrat namn. Fixar det!

Okej få läsa vidare i koden.

Tack för snabbt svar!
